FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./
COPY packages/api/package*.json ./packages/api/
COPY packages/core/package*.json ./packages/core/
COPY tsconfig.base.json ./
COPY prisma ./prisma

RUN npm pkg delete scripts.prepare && npm ci --workspace=packages/api --workspace=packages/core --include-workspace-root

RUN npx prisma generate

COPY packages/core/src ./packages/core/src
COPY packages/core/tsconfig.json ./packages/core/
RUN npm run build --workspace=packages/core

COPY packages/api/src ./packages/api/src
COPY packages/api/tsconfig.json ./packages/api/

RUN npm run build --workspace=packages/api

FROM node:22-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production

RUN apk add --no-cache openssl

COPY package*.json ./
COPY packages/api/package*.json ./packages/api/
COPY packages/core/package*.json ./packages/core/
COPY prisma ./prisma

RUN npm pkg delete scripts.prepare && npm ci --workspace=packages/api --omit=dev

COPY --from=builder /app/node_modules/.prisma ./node_modules/.prisma

COPY --from=builder /app/packages/core/dist ./packages/core/dist
COPY --from=builder /app/packages/api/dist ./packages/api/dist

EXPOSE 3000

CMD ["sh", "-c", "npx prisma migrate deploy && node packages/api/dist/index.js"]
